### ISSUE TITLE
Add a cache 

### ISSUE THREAD

**Issue by 45O** [azaelgg/meteoric#1]
If you do not add a cache to prevent previously redeemed codes or false codes from being re-entered.
You are certified gay

**Comment by azaelgg** [comment]
https://github.com/azaelgg/meteoric/blob/main/main.go#L62
https://github.com/azaelgg/meteoric/blob/main/main.go#L39
https://github.com/azaelgg/meteoric/blob/main/main.go#L40

Already added.
